//part1 navbar
$(document).ready(function(){
    $('.current-page').addClass('text-blue1');
})
//part3
$(document).ready(function(){
    $('.box2').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box2').addClass('text-light');
    }),
    $('.box2').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box2').removeClass('text-light');
    }),
    $('.box3').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box3').addClass('text-light');
    }),
    $('.box3').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box3').removeClass('text-light');
    }),
    $('.box4').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box4').addClass('text-light');
    }),
    $('.box4').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box4').removeClass('text-light');
    }),
    $('.box5').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box5').addClass('text-light');
    }),
    $('.box5').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box5').removeClass('text-light');
    }),
    $('.box6').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box6').addClass('text-light');
    }),
    $('.box6').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box6').removeClass('text-light');
    }),
    $('.box7').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box7').addClass('text-light');
    }),
    $('.box7').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box7').removeClass('text-light');
    }),
    $('.box8').mouseenter(function(){
        $(this).removeClass('bg-silver1'),
        $(this).addClass('bg-box1-part4'),
        $('.txt-box8').addClass('text-light');
    }),
    $('.box8').mouseleave(function(){
        $(this).removeClass('bg-box1-part4'),
        $(this).addClass('bg-silver1'),
        $('.txt-box8').removeClass('text-light');
    })
})
//part4
$(document).ready(function(){
    $('.box11').mouseenter(function(){
        $(this).removeClass('bg-silver2'),
        $(this).addClass('bg-img-part4-services'),
        $('.txt-box11').addClass('text-light');
    }),
    $('.box11').mouseleave(function(){
        $(this).removeClass('bg-img-part4-services'),
        $(this).addClass('bg-silver2'),
        $('.txt-box11').removeClass('text-light');
    }),
    $('.box22').mouseenter(function(){
        $(this).removeClass('bg-silver2'),
        $(this).addClass('bg-img-part4-services'),
        $('.txt-box22').addClass('text-light');
    }),
    $('.box22').mouseleave(function(){
        $(this).removeClass('bg-img-part4-services'),
        $(this).addClass('bg-silver2'),
        $('.txt-box22').removeClass('text-light');
    }),
    $('.box33').mouseenter(function(){
        $(this).removeClass('bg-silver2'),
        $(this).addClass('bg-img-part4-services'),
        $('.txt-box33').addClass('text-light');
    }),
    $('.box33').mouseleave(function(){
        $(this).removeClass('bg-img-part4-services'),
        $(this).addClass('bg-silver2'),
        $('.txt-box33').removeClass('text-light');
    })
})
//part6//footer
$(document).ready(function(){
    $('.icon1').mouseenter(function(){
        $('.bg-icon1').removeClass('bg-blue3'),
        $('.bg-icon1').addClass('bg-blue1');
    }),
    $('.icon1').mouseleave(function(){
        $('.bg-icon1').removeClass('bg-blue1'),
        $('.bg-icon1').addClass('bg-blue3');
    }),
    $('.icon2').mouseenter(function(){
        $('.bg-icon2').removeClass('bg-blue3'),
        $('.bg-icon2').addClass('bg-blue1');
    }),
    $('.icon2').mouseleave(function(){
        $('.bg-icon2').removeClass('bg-blue1'),
        $('.bg-icon2').addClass('bg-blue3');
    }),
    $('.icon3').mouseenter(function(){
        $('.bg-icon3').removeClass('bg-blue3'),
        $('.bg-icon3').addClass('bg-blue1');
    }),
    $('.icon3').mouseleave(function(){
        $('.bg-icon3').removeClass('bg-blue1'),
        $('.bg-icon3').addClass('bg-blue3');
    }),
    $('.icon4').mouseenter(function(){
        $('.bg-icon4').removeClass('bg-blue3'),
        $('.bg-icon4').addClass('bg-blue1');
    }),
    $('.icon4').mouseleave(function(){
        $('.bg-icon4').removeClass('bg-blue1'),
        $('.bg-icon4').addClass('bg-blue3');
    })
})